version: "3.8"

services:
  angular-frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
      - "49153:49153"
    volumes:
      - /app/node_modules
      - ./frontend/detQA:/app
